#3_AddUser-dataButton
rdbox-intec/rdboxGARIBAN2 pull request #6
Opened 2021-12-09 07:42 UTC by 3hoK

「Set user-data」ボタンを追加しました

2021-12-09 23:43 UTC, fukuta-tatsuya-intec requested changes
ファイル名及び、インスタンスは省略名を使用しないようにして下さい。
（他のコンポーネントと合わせた形が良いかと思います。）
- ud-setter.tsx → userdata-setter.tsx
- UDSetter → UserdataSetter

2021-12-09 23:45 UTC, fukuta-tatsuya-intec commented
Lintは問題ありませんでした。

$ npm run lint         

> balena-etcher@1.7.0 lint
> npm run lint-ts && npm run lint-css


> balena-etcher@1.7.0 lint-ts
> balena-lint --fix --typescript typings lib tests scripts/clean-shrinkwrap.ts webpack.config.ts

0 errors and 0 warnings in 77 files

> balena-etcher@1.7.0 lint-css
> prettier --write lib/**/*.css

2021-12-09 23:48 UTC, fukuta-tatsuya-intec commented
見た目もGoodです！

<img width="1312" alt="スクリーンショット 2021-12-10 8 36 27" src="https://user-images.githubusercontent.com/40556102/145493355-e984f255-33cb-47eb-b739-7a2dc0af52e2.png">
<img width="1312" alt="スクリーンショット 2021-12-10 8 37 05" src="https://user-images.githubusercontent.com/40556102/145493360-6d843407-0c33-4ec7-a74e-d80cbe43d94e.png">

2021-12-10 02:58 UTC, 3hoK commented
>ファイル名及び、インスタンスは省略名を使用しないようにして下さい。
>（他のコンポーネントと合わせた形が良いかと思います。）
>
>ud-setter.tsx → userdata-setter.tsx
>UDSetter → UserdataSetter

現GARIBANのファイル名を使った方が分かりやすいかと思い、上記にしましたが、
今回を機会に変えたいという事ですね。承知致しました。

2021-12-10 07:18 UTC, 3hoK commented
> ファイル名及び、インスタンスは省略名を使用しないようにして下さい。 （他のコンポーネントと合わせた形が良いかと思います。）
> 
> * ud-setter.tsx → userdata-setter.tsx
> * UDSetter → UserdataSetter

ファイル名を修正しました。

2021-12-10 07:26 UTC, fukuta-tatsuya-intec reviewed
OK!

2021-12-10 07:26 UTC, fukuta-tatsuya-intec approved these changes

2021-12-10 07:32 UTC, merged